openapi: 3.0.0
servers:
  - description: Localhost
    url: http://localhost:8080
info:
  description: This is a sample backend
  version: v1
  title: Sample Backend
  contact:
    email: renukapiyumal@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
tags:
  - name: hotels
    description: Hotels
  - name: petfoods
    description: Pet foods
  - name: news
    description: News Feed
  - name: weather
    description: Current weather
  - name: forecast
    description: Forecast weather
paths:
  /hotels:
    get:
      tags:
        - hotels
      summary: Top hotels
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HotelList"

  /petfoods:
    get:
      tags:
        - petfoods
      summary: Pet Foods
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PetFoodList"

  /top-headlines:
    get:
      tags:
        - news
      summary: Top news
      description: Top news of the day
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Headline"

  /weather:
    get:
      tags:
        - weather
      summary: Current weather
      description: Weather by city name
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
            enum:
              - Mountain View
              - Denver
              - Boston
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrentWeather"
        404:
          description: City not found
  /forecast/hourly:
    get:
      tags:
        - forecast
      summary: Forecasted weather
      description: Forecasted weather by city name
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
            enum:
              - Mountain View
              - Denver
              - Boston
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForecastWeather"
        404:
          description: City not found
components:
  schemas:
    HotelList:
      type: object
      properties:
        countryCode:
          type: string
          example: US
        stateCode:
          type: string
          example: CA
        lat:
          type: number
          example: 37.655757904052734
        lon:
          type: number
          example: -122.41319274902344
        count:
          type: integer
          example: 1
        hotels:
          type: object
          properties:
            brand:
              type: string
              example: Hilton
            name:
              type: string
              example: Parc 55 San Francisco - A Hilton Hotel
            starRating:
              type: number
              example: 4
            overallGuestRating:
              type: number
              example: 8
            totalReviewCount:
              type: integer
              example: 1580
    PetFoodList:
      type: object
      properties:
        count:
          type: integer
          example: 1
        list:
          type: array
          items:
            $ref: "#/components/schemas/PetFood"
    PetFood:
      type: object
      properties:
        id:
          type: integer
          example: 1
        category:
          type: string
          example: dog
        manufacturer:
          type: string
          example: Just Food For Dogs
        name:
          type: string
          example: JustFoodForDogs Chicken & White Rice Frozen Cooked Dog Food
        price:
          type: number
          example: 7.99
        details:
          type: string
          example: Just Food for Dogs Chicken and White Rice Recipe features 100% ingredients approved for human consumption. This adult life stage dog food is all natural, healthy, and made by hand in small batches in Southern California.
        ingredients:
          type: string
          example: Chicken Thigh, Long Grain White Rice, Spinach, Carrots, Apples, Chicken Gizzard, Chicken Liver
    Headline:
      type: object
      properties:
        count:
          type: integer
          example: 1
        articles:
          type: object
          properties:
            source:
              type: string
              example: CNN
            author:
              type: string
              example: Madeline Holcombe, CNN
            title:
              type: string
              example: Covid-19 herd immunity is a difficult target, experts warn, but vaccinating teens could be key to protecting us this fall - CNN
            description:
              type: string
              example: Vaccinations could soon open up for children 12 to 15 years old, a development that could be key to protecting the United States against Covid-19 as overall vaccination rates slow.
            url:
              type: string
              example: https://www.cnn.com/2021/05/06/health/us-coronavirus-thursday/index.html
            urlToImage:
              type: string
              example: https://cdn.cnn.com/cnnnext/dam/assets/210506023823-us-coronavirus-0420-restricted-super-tease.jpg
            publishedAt:
              type: string
              format: date-time
              example: "2021-05-06T10:18:00Z"
            content:
              type: string
              example: (CNN)Vaccinations could soon open up for children 12 to 15 years old, a development that could be key to protecting the United States against Covid-19 as overall vaccination rates slow.

    CurrentWeather:
      type: object
      properties:
        country:
          type: string
          example: US
        city:
          type: string
          example: Mountain View
        timezone:
          type: integer
          example: -25200
        weather:
          $ref: "#/components/schemas/Weather"
    ForecastWeather:
      type: object
      properties:
        country:
          type: string
          example: US
        city:
          type: string
          example: Mountain View
        timezone:
          type: integer
          example: -25200
        count:
          type: integer
          example: 1
        list:
          type: array
          items:
            $ref: "#/components/schemas/Weather"
    Weather:
      type: object
      properties:
        datetime:
          type: integer
          example: 1620280800
        temp:
          type: number
          example: 282.55
        feels_like:
          type: number
          example: 281.86
        pressure:
          type: integer
          example: 1023
        humidity:
          type: integer
          example: 100
