apiVersion: v1
kind: Service
metadata:
  name: products-backend
  labels:
    app: products-backend
spec:
  type: NodePort
  ports:
  - name: products
    port: 8080
    targetPort: 8080
    nodePort: 30100
  selector:
    app: products-backend
