apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-${NAME}
  labels:
    app: MyApp-${NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyApp-${NAME}
  template:
    metadata:
      labels:
        app: MyApp-${NAME}
    spec:
      containers:
      - name: my-backend-${NAME}
        image: cakebakery/request-info:v1
        resources:
          limits:
            cpu: "5m"
            memory: "10Mi"
          requests:
            cpu: "2m"
            memory: "5Mi"
        env:
          - name: NAME
            value: "Service ${NAME}"
        args:
          - "-pretty"
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: my-service-${NAME}
spec:
  selector:
    app: MyApp-${NAME}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
