apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: backend-2
  name: backend-2
spec:
  ports:
  - name: proxy-http-port
    port: 9090
    protocol: TCP
    targetPort: http-port
  selector:
    choreo.component: backend-2
