/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
)

func HotelsGet(w http.ResponseWriter, r *http.Request) {
	res := `{
  "countryCode": "US",
  "lat": 37.655757904052734,
  "lon": -122.41319274902344,
  "stateCode": "CA",
  "count": 2,
  "hotels": [
    {
      "brand": "Hilton",
      "name": "Parc 55 San Francisco - A Hilton Hotel",
      "starRating": 4,
      "overallGuestRating": 8,
      "totalReviewCount": 1580
    },
    {
      "brand": "Intercontinental",
      "name": "Intercontinental San Francisco",
      "starRating": 4.5,
      "overallGuestRating": 8.6,
      "totalReviewCount": 658
    }
  ]
}`
	if _, err := w.Write([]byte(res)); err != nil {
		panic(err)
	}
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
