/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
)

func ForecastHourlyGet(w http.ResponseWriter, r *http.Request) {
	res := `{
  "timezone": -25200,
  "country": "US",
  "city": "Mountain View",
  "count": 3,
  "list": [
    {
      "datetime": 1620280800,
      "temp": 282.55,
      "feels_like": 281.86,
      "pressure": 1023,
      "humidity": 100,
      "wind_speed": 1.5,
      "wind_deg": 350
    },
    {
      "datetime": 1620284400,
      "temp": 283.55,
      "feels_like": 282.86,
      "pressure": 1023,
      "humidity": 100,
      "wind_speed": 1.5,
      "wind_deg": 350
    },
    {
      "datetime": 1620288000,
      "temp": 281.55,
      "feels_like": 280.86,
      "pressure": 1023,
      "humidity": 100,
      "wind_speed": 1.5,
      "wind_deg": 350
    }
  ]
}`
	if _, err := w.Write([]byte(res)); err != nil {
		panic(err)
	}
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
