/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
)

func TopHeadlinesGet(w http.ResponseWriter, r *http.Request) {
	res := `{
  "count": 3,
  "articles": [
    {
      "source": "CNN",
      "author": "Madeline Holcombe, CNN",
      "title": "Covid-19 herd immunity is a difficult target, experts warn, but vaccinating teens could be key to protecting us this fall - CNN ",
      "description": "Vaccinations could soon open up for children 12 to 15 years old, a development that could be key to protecting the United States against Covid-19 as overall vaccination rates slow.",
      "url": "https://www.cnn.com/2021/05/06/health/us-coronavirus-thursday/index.html",
      "urlToImage": "https://cdn.cnn.com/cnnnext/dam/assets/210506023823-us-coronavirus-0420-restricted-super-tease.jpg",
      "publishedAt": "2021-05-06T10:18:00Z",
      "content": "(CNN)Vaccinations could soon open up for children 12 to 15 years old, a development that could be key to protecting the United States against Covid-19 as overall vaccination rates slow.\r\n\"High school… [+5034 chars]"
    },
    {
      "source": "New York Times",
      "author": "Andrew Testa, Stephen Castle",
      "title": "Scottish Election Could Boost Independence Movement - The New York Times",
      "description": "If the pro-independence vote surges in Thursday’s elections for the Scottish Parliament, momentum for an another referendum on independence may become unstoppable.",
      "url": "https://www.nytimes.com/2021/05/06/world/scotland-election-brexit-independence.html",
      "urlToImage": "https://static01.nyt.com/images/2021/05/06/world/06Scotland-Photos/06Scotland-Photos-facebookJumbo.jpg",
      "publishedAt": "2021-05-06T07:03:40Z",
      "content": "Mr. Johnson not only proceeded with Brexit, but also brushed aside Scottish calls to keep close ties to the European Union and opted instead for a bare-bones trade deal with the bloc that has caused … [+895 chars]"
    },
    {
      "source": "CNN",
      "author": "Kevin Dotson",
      "title": "Orioles pitcher could have had a perfect game, but for one weird baseball rule - CNN International",
      "description": "Baltimore Orioles pitcher John Means threw the third no-hitter of the 2021 MLB season Wednesday against the Seattle Mariners -- and might have thrown a perfect game but for one weird baseball rule after a strikeout.",
      "url": "https://edition.cnn.com/2021/05/05/sport/john-means-orioles-pitcher-no-hitter-mariners-spt/index.html",
      "urlToImage": "https://cdn.cnn.com/cnnnext/dam/assets/210505200723-john-means-0505-super-tease.jpg",
      "publishedAt": "2021-05-06T01:17:22Z",
      "content": "(CNN)Baltimore Orioles pitcher John Means threw the third no-hitter of the 2021 MLB season Wednesday against the Seattle Mariners -- and might have thrown a perfect game but for one weird baseball ru… [+1265 chars]"
    }
  ]
}`
	if _, err := w.Write([]byte(res)); err != nil {
		panic(err)
	}
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
