/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HotelListHotels struct {
	Brand string `json:"brand,omitempty"`

	Name string `json:"name,omitempty"`

	StarRating float64 `json:"starRating,omitempty"`

	OverallGuestRating float64 `json:"overallGuestRating,omitempty"`

	TotalReviewCount int32 `json:"totalReviewCount,omitempty"`
}
