/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HotelList struct {
	CountryCode string `json:"countryCode,omitempty"`

	StateCode string `json:"stateCode,omitempty"`

	Lat float64 `json:"lat,omitempty"`

	Lon float64 `json:"lon,omitempty"`

	Count int32 `json:"count,omitempty"`

	Hotels *HotelListHotels `json:"hotels,omitempty"`
}
