/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Headline struct {
	Count int32 `json:"count,omitempty"`

	Articles *HeadlineArticles `json:"articles,omitempty"`
}
