/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type HeadlineArticles struct {
	Source string `json:"source,omitempty"`

	Author string `json:"author,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	Url string `json:"url,omitempty"`

	UrlToImage string `json:"urlToImage,omitempty"`

	PublishedAt time.Time `json:"publishedAt,omitempty"`

	Content string `json:"content,omitempty"`
}
