/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ForecastWeather struct {
	Country string `json:"country,omitempty"`

	City string `json:"city,omitempty"`

	Timezone int32 `json:"timezone,omitempty"`

	Count int32 `json:"count,omitempty"`

	List []Weather `json:"list,omitempty"`
}
