/*
 * Sample Backend
 *
 * This is a sample backend
 *
 * API version: v1
 * Contact: renukapiyumal@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PetFood struct {
	Id int32 `json:"id,omitempty"`

	Category string `json:"category,omitempty"`

	Manufacturer string `json:"manufacturer,omitempty"`

	Name string `json:"name,omitempty"`

	Price float64 `json:"price,omitempty"`

	Details string `json:"details,omitempty"`

	Ingredients string `json:"ingredients,omitempty"`
}
