version: "3.7"
services:
  # Envoy Proxy
  envoy:
    image: envoyproxy/envoy:v1.19.0
    command: -c /etc/envoy/envoy.yaml
    # command: -c /etc/envoy/envoy.yaml --component-log-level conn_handler:trace,connection:trace,client:trace
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./lib/json.lua:/lib/json.lua
      - ./lib/base64.lua:/lib/base64.lua
      - ./lua-scripts:/etc/lua
      - ./certs:/certs
    ports:
      - 8080:8080
      - 9000:9000
