apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: backend-1
  name: backend-1
spec:
  ports:
  - name: proxy-http-port
    port: 8688
    protocol: TCP
    targetPort: http-port
  selector:
    choreo.component: backend-1
